// ===================================================
// Reels/Shorts — Export Engine
// ===================================================

import type { VideoTemplate } from './types';
import { generateShotList } from './generator';

// ===================================================
// exportAsJSON
// ===================================================

/**
 * Full template data as a JSON string — ideal for custom video editors.
 */
export function exportAsJSON(template: VideoTemplate): string {
  return JSON.stringify(template, null, 2);
}

// ===================================================
// exportAsShotList
// ===================================================

/**
 * Human-readable shot list in markdown format.
 */
export function exportAsShotList(template: VideoTemplate): string {
  const shots = generateShotList(template);
  const lines: string[] = [
    `# Shot List — ${template.name}`,
    `**Duration:** ${template.totalDurationMs / 1000}s  |  **Category:** ${template.category}`,
    `**Formats:** ${template.formats.join(', ')}`,
    '',
    '---',
    '',
  ];

  for (const shot of shots) {
    lines.push(`## Shot ${shot.shotNumber} — ${shot.sectionLabel}`);
    lines.push(`**Time:** ${shot.startTime} → ${shot.endTime} (${shot.durationSec}s)`);
    lines.push(`**Visual:** ${shot.visualDescription}`);
    lines.push(`**Animation:** ${shot.animationStyle}`);
    if (shot.textOverlays.length > 0) {
      lines.push(`**Text Overlays:**`);
      shot.textOverlays.forEach((t) => lines.push(`  - ${t}`));
    }
    if (shot.notes) {
      lines.push(`**Production Note:** ${shot.notes}`);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push(`*Generated by SpotifyAdCurator · ${new Date().toLocaleDateString()}*`);

  return lines.join('\n');
}

// ===================================================
// exportAsCSV
// ===================================================

/**
 * Spreadsheet-friendly CSV — one row per text overlay.
 */
export function exportAsCSV(template: VideoTemplate): string {
  const header = [
    'Shot #',
    'Section',
    'Start (s)',
    'End (s)',
    'Duration (s)',
    'Text Content',
    'Position',
    'Font Size',
    'Color',
    'Animation',
    'Animation Delay (ms)',
    'Bold',
    'Italic',
    'Notes',
  ].join(',');

  const rows: string[] = [header];

  template.sections.forEach((section, idx) => {
    const startSec = (section.startMs / 1000).toFixed(1);
    const endSec = ((section.startMs + section.durationMs) / 1000).toFixed(1);
    const durSec = (section.durationMs / 1000).toFixed(1);

    if (section.textOverlays.length === 0) {
      rows.push(
        [
          idx + 1,
          section.label,
          startSec,
          endSec,
          durSec,
          '(no text)',
          '',
          '',
          '',
          section.animationStyle,
          '',
          '',
          '',
          section.notes ?? '',
        ]
          .map((v) => `"${String(v).replace(/"/g, '""')}"`)
          .join(',')
      );
    } else {
      section.textOverlays.forEach((overlay) => {
        rows.push(
          [
            idx + 1,
            section.label,
            startSec,
            endSec,
            durSec,
            overlay.content,
            overlay.position,
            overlay.fontSize,
            overlay.color,
            overlay.animation,
            overlay.animationDelay ?? 0,
            overlay.bold ? 'Yes' : 'No',
            overlay.italic ? 'Yes' : 'No',
            section.notes ?? '',
          ]
            .map((v) => `"${String(v).replace(/"/g, '""')}"`)
            .join(',')
        );
      });
    }
  });

  return rows.join('\n');
}

// ===================================================
// generateCapCutProject
// ===================================================

/**
 * CapCut-compatible project structure (JSON).
 * Based on CapCut desktop project schema conventions.
 */
export function generateCapCutProject(template: VideoTemplate): string {
  const tracks = template.sections.map((section, idx) => ({
    id: `track_${idx}`,
    type: 'video',
    start: section.startMs * 1000, // CapCut uses microseconds
    duration: section.durationMs * 1000,
    extra_material_refs: [],
    clip: {
      alpha: 1.0,
      flip: { horizontal: false, vertical: false },
      rotation: 0.0,
      scale: { x: 1.0, y: 1.0 },
      transform: { x: 0.0, y: 0.0 },
    },
    color: section.backgroundColorHex,
    animation: section.animationStyle,
  }));

  const textTracks = template.sections.flatMap((section, secIdx) =>
    section.textOverlays.map((overlay, oIdx) => ({
      id: `text_${secIdx}_${oIdx}`,
      type: 'text',
      start: (section.startMs + (overlay.animationDelay ?? 0)) * 1000,
      duration: (section.durationMs - (overlay.animationDelay ?? 0)) * 1000,
      content: overlay.content,
      style: {
        font_size: overlay.fontSize,
        color: overlay.color,
        bold: overlay.bold ?? false,
        italic: overlay.italic ?? false,
        position: overlay.position,
      },
      animation: {
        in: overlay.animation,
        out: 'fade',
      },
    }))
  );

  const project = {
    id: `capcut_${template.id}_${Date.now()}`,
    name: template.name,
    create_time: Math.floor(Date.now() / 1000),
    fps: 30,
    duration: template.totalDurationMs * 1000,
    canvas_config: {
      width: 1080,
      height: 1920,
      ratio: '9:16',
    },
    color_space: 0,
    tracks,
    text_tracks: textTracks,
    description: template.description,
    generated_by: 'SpotifyAdCurator',
  };

  return JSON.stringify(project, null, 2);
}

// ===================================================
// generateFFmpegScript
// ===================================================

/**
 * Basic FFmpeg command suggestions — useful as a starting point for
 * developers rendering the template programmatically.
 */
export function generateFFmpegScript(template: VideoTemplate): string {
  const lines: string[] = [
    `#!/bin/bash`,
    `# FFmpeg Script — ${template.name}`,
    `# Generated by SpotifyAdCurator on ${new Date().toLocaleDateString()}`,
    `# Duration: ${template.totalDurationMs / 1000}s | Format: 1080x1920 (9:16)`,
    ``,
    `# Prerequisites: ffmpeg >= 5.0`,
    `# Replace INPUT_VIDEO with your actual video file paths.`,
    ``,
    `OUTPUT="output_${template.id}.mp4"`,
    ``,
  ];

  template.sections.forEach((section, idx) => {
    const startSec = (section.startMs / 1000).toFixed(2);
    const durSec = (section.durationMs / 1000).toFixed(2);
    lines.push(`# --- Section ${idx + 1}: ${section.label} (${startSec}s – ${(parseFloat(startSec) + parseFloat(durSec)).toFixed(2)}s) ---`);
    lines.push(`# Background colour: ${section.backgroundColorHex} | Animation: ${section.animationStyle}`);

    section.textOverlays.forEach((overlay, oIdx) => {
      const delay = (overlay.animationDelay ?? 0) / 1000;
      const textStart = parseFloat(startSec) + delay;
      lines.push(
        `# Text overlay ${oIdx + 1}: "${overlay.content}" @ ${overlay.position} [${overlay.fontSize}] from ${textStart.toFixed(2)}s`
      );
    });

    lines.push(
      `ffmpeg -i INPUT_VIDEO_${idx}.mp4 \\`,
      `  -ss ${startSec} -t ${durSec} \\`,
      `  -vf "scale=1080:1920:force_original_aspect_ratio=decrease,pad=1080:1920:(ow-iw)/2:(oh-ih)/2:${section.backgroundColorHex}" \\`,
      `  -c:v libx264 -preset fast -crf 22 \\`,
      `  segment_${idx}.mp4`,
      ``
    );
  });

  lines.push(
    `# Create concat list`,
    `cat > concat_list.txt << 'EOF'`,
    ...template.sections.map((_, idx) => `file 'segment_${idx}.mp4'`),
    `EOF`,
    ``,
    `# Concatenate segments`,
    `ffmpeg -f concat -safe 0 -i concat_list.txt -c copy "$OUTPUT"`,
    ``,
    `echo "Done! Output: $OUTPUT"`,
  );

  return lines.join('\n');
}
