import type { CountryTarget } from '../../types';

// Genre → Best countries to target with CPM/CPC estimates
export const GENRE_COUNTRY_MAP: Record<string, CountryTarget[]> = {
  afrobeats: [
    { code: 'NG', name: 'Nigeria', flag: '🇳🇬', estimatedCpm: 0.8, estimatedCpc: 0.05, audienceSize: '12M+', primaryReason: 'Origin market, highest organic affinity', score: 98 },
    { code: 'GH', name: 'Ghana', flag: '🇬🇭', estimatedCpm: 0.7, estimatedCpc: 0.04, audienceSize: '3M+', primaryReason: 'Strong Afrobeats culture', score: 92 },
    { code: 'GB', name: 'United Kingdom', flag: '🇬🇧', estimatedCpm: 3.5, estimatedCpc: 0.25, audienceSize: '8M+', primaryReason: 'Large diaspora, Afrobeats is mainstream', score: 88 },
    { code: 'US', name: 'United States', flag: '🇺🇸', estimatedCpm: 8.0, estimatedCpc: 0.60, audienceSize: '25M+', primaryReason: 'Huge African-American audience', score: 80 },
    { code: 'ZA', name: 'South Africa', flag: '🇿🇦', estimatedCpm: 1.2, estimatedCpc: 0.08, audienceSize: '5M+', primaryReason: 'Growing Afrobeats fanbase', score: 85 },
  ],
  'k-pop': [
    { code: 'KR', name: 'South Korea', flag: '🇰🇷', estimatedCpm: 2.5, estimatedCpc: 0.18, audienceSize: '15M+', primaryReason: 'Origin market', score: 99 },
    { code: 'PH', name: 'Philippines', flag: '🇵🇭', estimatedCpm: 0.6, estimatedCpc: 0.04, audienceSize: '20M+', primaryReason: 'World\'s most passionate K-Pop fanbase per capita', score: 97 },
    { code: 'ID', name: 'Indonesia', flag: '🇮🇩', estimatedCpm: 0.5, estimatedCpc: 0.03, audienceSize: '30M+', primaryReason: 'Massive K-Pop community, low CPM', score: 95 },
    { code: 'US', name: 'United States', flag: '🇺🇸', estimatedCpm: 8.0, estimatedCpc: 0.60, audienceSize: '15M+', primaryReason: 'Large K-Pop fandom', score: 82 },
    { code: 'JP', name: 'Japan', flag: '🇯🇵', estimatedCpm: 4.0, estimatedCpc: 0.30, audienceSize: '12M+', primaryReason: 'Deep K-Pop penetration', score: 88 },
  ],
  latin: [
    { code: 'MX', name: 'Mexico', flag: '🇲🇽', estimatedCpm: 1.0, estimatedCpc: 0.07, audienceSize: '40M+', primaryReason: 'Latin music heartland', score: 99 },
    { code: 'CO', name: 'Colombia', flag: '🇨🇴', estimatedCpm: 0.9, estimatedCpc: 0.06, audienceSize: '18M+', primaryReason: 'Reggaeton origin country', score: 96 },
    { code: 'BR', name: 'Brazil', flag: '🇧🇷', estimatedCpm: 1.1, estimatedCpc: 0.08, audienceSize: '60M+', primaryReason: 'Largest Latin market', score: 94 },
    { code: 'US', name: 'United States', flag: '🇺🇸', estimatedCpm: 8.0, estimatedCpc: 0.60, audienceSize: '35M+', primaryReason: 'Hispanic streaming market leader', score: 85 },
    { code: 'ES', name: 'Spain', flag: '🇪🇸', estimatedCpm: 2.5, estimatedCpc: 0.20, audienceSize: '15M+', primaryReason: 'Native Spanish market', score: 90 },
  ],
  reggaeton: [
    { code: 'MX', name: 'Mexico', flag: '🇲🇽', estimatedCpm: 1.0, estimatedCpc: 0.07, audienceSize: '40M+', primaryReason: 'Massive Reggaeton fanbase', score: 98 },
    { code: 'CO', name: 'Colombia', flag: '🇨🇴', estimatedCpm: 0.9, estimatedCpc: 0.06, audienceSize: '18M+', primaryReason: 'Origin market for Reggaeton', score: 99 },
    { code: 'PR', name: 'Puerto Rico', flag: '🇵🇷', estimatedCpm: 2.0, estimatedCpc: 0.15, audienceSize: '2M+', primaryReason: 'Reggaeton birthplace', score: 97 },
    { code: 'US', name: 'United States', flag: '🇺🇸', estimatedCpm: 8.0, estimatedCpc: 0.60, audienceSize: '35M+', primaryReason: 'Large Latino population', score: 84 },
    { code: 'AR', name: 'Argentina', flag: '🇦🇷', estimatedCpm: 1.0, estimatedCpc: 0.07, audienceSize: '15M+', primaryReason: 'Strong Latin music market', score: 87 },
  ],
  pop: [
    { code: 'US', name: 'United States', flag: '🇺🇸', estimatedCpm: 8.0, estimatedCpc: 0.60, audienceSize: '100M+', primaryReason: 'Global pop music capital', score: 95 },
    { code: 'GB', name: 'United Kingdom', flag: '🇬🇧', estimatedCpm: 3.5, estimatedCpc: 0.25, audienceSize: '30M+', primaryReason: 'Major pop market', score: 92 },
    { code: 'CA', name: 'Canada', flag: '🇨🇦', estimatedCpm: 4.0, estimatedCpc: 0.30, audienceSize: '18M+', primaryReason: 'English-speaking, high engagement', score: 88 },
    { code: 'AU', name: 'Australia', flag: '🇦🇺', estimatedCpm: 3.8, estimatedCpc: 0.28, audienceSize: '12M+', primaryReason: 'Strong English pop market', score: 87 },
    { code: 'DE', name: 'Germany', flag: '🇩🇪', estimatedCpm: 3.0, estimatedCpc: 0.22, audienceSize: '20M+', primaryReason: 'Largest European music market', score: 84 },
  ],
  'hip-hop': [
    { code: 'US', name: 'United States', flag: '🇺🇸', estimatedCpm: 8.0, estimatedCpc: 0.60, audienceSize: '80M+', primaryReason: 'Hip-Hop birthplace and biggest market', score: 99 },
    { code: 'GB', name: 'United Kingdom', flag: '🇬🇧', estimatedCpm: 3.5, estimatedCpc: 0.25, audienceSize: '20M+', primaryReason: 'UK Drill scene, massive hip-hop culture', score: 92 },
    { code: 'FR', name: 'France', flag: '🇫🇷', estimatedCpm: 2.8, estimatedCpc: 0.20, audienceSize: '18M+', primaryReason: '#1 hip-hop market in Europe', score: 90 },
    { code: 'DE', name: 'Germany', flag: '🇩🇪', estimatedCpm: 3.0, estimatedCpc: 0.22, audienceSize: '15M+', primaryReason: 'Strong German rap scene', score: 85 },
    { code: 'NG', name: 'Nigeria', flag: '🇳🇬', estimatedCpm: 0.8, estimatedCpc: 0.05, audienceSize: '10M+', primaryReason: 'Afro-hip-hop crossover market', score: 82 },
  ],
  rap: [
    { code: 'US', name: 'United States', flag: '🇺🇸', estimatedCpm: 8.0, estimatedCpc: 0.60, audienceSize: '80M+', primaryReason: 'Core rap market', score: 99 },
    { code: 'GB', name: 'United Kingdom', flag: '🇬🇧', estimatedCpm: 3.5, estimatedCpc: 0.25, audienceSize: '20M+', primaryReason: 'Grime and UK Rap scene', score: 91 },
    { code: 'FR', name: 'France', flag: '🇫🇷', estimatedCpm: 2.8, estimatedCpc: 0.20, audienceSize: '18M+', primaryReason: 'Europe\'s rap capital', score: 89 },
    { code: 'CA', name: 'Canada', flag: '🇨🇦', estimatedCpm: 4.0, estimatedCpc: 0.30, audienceSize: '12M+', primaryReason: 'Drake effect, major rap market', score: 87 },
    { code: 'AU', name: 'Australia', flag: '🇦🇺', estimatedCpm: 3.8, estimatedCpc: 0.28, audienceSize: '8M+', primaryReason: 'Growing Australian hip-hop scene', score: 82 },
  ],
  'r&b': [
    { code: 'US', name: 'United States', flag: '🇺🇸', estimatedCpm: 8.0, estimatedCpc: 0.60, audienceSize: '60M+', primaryReason: 'R&B heartland', score: 99 },
    { code: 'GB', name: 'United Kingdom', flag: '🇬🇧', estimatedCpm: 3.5, estimatedCpc: 0.25, audienceSize: '15M+', primaryReason: 'Strong R&B culture, UK Soul scene', score: 90 },
    { code: 'ZA', name: 'South Africa', flag: '🇿🇦', estimatedCpm: 1.2, estimatedCpc: 0.08, audienceSize: '8M+', primaryReason: 'Deep R&B roots, low CPM', score: 85 },
    { code: 'NG', name: 'Nigeria', flag: '🇳🇬', estimatedCpm: 0.8, estimatedCpc: 0.05, audienceSize: '10M+', primaryReason: 'Afro-R&B crossover market', score: 83 },
    { code: 'CA', name: 'Canada', flag: '🇨🇦', estimatedCpm: 4.0, estimatedCpc: 0.30, audienceSize: '10M+', primaryReason: 'Strong R&B streaming market', score: 86 },
  ],
  soul: [
    { code: 'US', name: 'United States', flag: '🇺🇸', estimatedCpm: 8.0, estimatedCpc: 0.60, audienceSize: '50M+', primaryReason: 'Soul music origin', score: 99 },
    { code: 'GB', name: 'United Kingdom', flag: '🇬🇧', estimatedCpm: 3.5, estimatedCpc: 0.25, audienceSize: '15M+', primaryReason: 'Northern Soul, UK Soul scene', score: 91 },
    { code: 'ZA', name: 'South Africa', flag: '🇿🇦', estimatedCpm: 1.2, estimatedCpc: 0.08, audienceSize: '7M+', primaryReason: 'Soul music deeply embedded', score: 85 },
    { code: 'NG', name: 'Nigeria', flag: '🇳🇬', estimatedCpm: 0.8, estimatedCpc: 0.05, audienceSize: '8M+', primaryReason: 'Soul/R&B crossover', score: 82 },
    { code: 'AU', name: 'Australia', flag: '🇦🇺', estimatedCpm: 3.8, estimatedCpc: 0.28, audienceSize: '6M+', primaryReason: 'Strong soul/jazz fanbase', score: 80 },
  ],
  edm: [
    { code: 'NL', name: 'Netherlands', flag: '🇳🇱', estimatedCpm: 2.8, estimatedCpc: 0.20, audienceSize: '8M+', primaryReason: 'EDM capital of the world (ADE, Tiësto, Martin Garrix)', score: 99 },
    { code: 'DE', name: 'Germany', flag: '🇩🇪', estimatedCpm: 3.0, estimatedCpc: 0.22, audienceSize: '20M+', primaryReason: 'Techno/House origin, Berghain culture', score: 97 },
    { code: 'GB', name: 'United Kingdom', flag: '🇬🇧', estimatedCpm: 3.5, estimatedCpc: 0.25, audienceSize: '20M+', primaryReason: 'Rave culture roots, massive EDM scene', score: 94 },
    { code: 'US', name: 'United States', flag: '🇺🇸', estimatedCpm: 8.0, estimatedCpc: 0.60, audienceSize: '50M+', primaryReason: 'EDM festivals (EDC, Ultra, Coachella)', score: 88 },
    { code: 'SE', name: 'Sweden', flag: '🇸🇪', estimatedCpm: 3.2, estimatedCpc: 0.23, audienceSize: '5M+', primaryReason: 'Avicii, Swedish House Mafia origin', score: 93 },
  ],
  dance: [
    { code: 'NL', name: 'Netherlands', flag: '🇳🇱', estimatedCpm: 2.8, estimatedCpc: 0.20, audienceSize: '8M+', primaryReason: 'Dance music capital', score: 98 },
    { code: 'GB', name: 'United Kingdom', flag: '🇬🇧', estimatedCpm: 3.5, estimatedCpc: 0.25, audienceSize: '20M+', primaryReason: 'Dance music culture', score: 94 },
    { code: 'DE', name: 'Germany', flag: '🇩🇪', estimatedCpm: 3.0, estimatedCpc: 0.22, audienceSize: '18M+', primaryReason: 'Techno/Dance heartland', score: 93 },
    { code: 'US', name: 'United States', flag: '🇺🇸', estimatedCpm: 8.0, estimatedCpc: 0.60, audienceSize: '45M+', primaryReason: 'Huge dance music fanbase', score: 87 },
    { code: 'AU', name: 'Australia', flag: '🇦🇺', estimatedCpm: 3.8, estimatedCpc: 0.28, audienceSize: '8M+', primaryReason: 'Strong festival culture', score: 86 },
  ],
  jazz: [
    { code: 'US', name: 'United States', flag: '🇺🇸', estimatedCpm: 8.0, estimatedCpc: 0.60, audienceSize: '20M+', primaryReason: 'Jazz birthplace (New Orleans, NYC)', score: 99 },
    { code: 'JP', name: 'Japan', flag: '🇯🇵', estimatedCpm: 4.0, estimatedCpc: 0.30, audienceSize: '15M+', primaryReason: 'World\'s #2 jazz market, huge vinyl culture', score: 96 },
    { code: 'FR', name: 'France', flag: '🇫🇷', estimatedCpm: 2.8, estimatedCpc: 0.20, audienceSize: '10M+', primaryReason: 'Jazz stronghold in Europe', score: 92 },
    { code: 'GB', name: 'United Kingdom', flag: '🇬🇧', estimatedCpm: 3.5, estimatedCpc: 0.25, audienceSize: '8M+', primaryReason: 'Strong jazz scene (London, Manchester)', score: 88 },
    { code: 'DE', name: 'Germany', flag: '🇩🇪', estimatedCpm: 3.0, estimatedCpc: 0.22, audienceSize: '7M+', primaryReason: 'Active jazz festival circuit', score: 85 },
  ],
  country: [
    { code: 'US', name: 'United States', flag: '🇺🇸', estimatedCpm: 8.0, estimatedCpc: 0.60, audienceSize: '80M+', primaryReason: 'Country music heartland (Nashville)', score: 99 },
    { code: 'CA', name: 'Canada', flag: '🇨🇦', estimatedCpm: 4.0, estimatedCpc: 0.30, audienceSize: '10M+', primaryReason: 'Strong country/Americana market', score: 90 },
    { code: 'AU', name: 'Australia', flag: '🇦🇺', estimatedCpm: 3.8, estimatedCpc: 0.28, audienceSize: '8M+', primaryReason: 'Country music culture (Tamworth)', score: 88 },
    { code: 'GB', name: 'United Kingdom', flag: '🇬🇧', estimatedCpm: 3.5, estimatedCpc: 0.25, audienceSize: '6M+', primaryReason: 'Growing UK country/Americana scene', score: 82 },
    { code: 'IE', name: 'Ireland', flag: '🇮🇪', estimatedCpm: 2.5, estimatedCpc: 0.18, audienceSize: '2M+', primaryReason: 'Folk/Country deeply embedded', score: 85 },
  ],
  indie: [
    { code: 'GB', name: 'United Kingdom', flag: '🇬🇧', estimatedCpm: 3.5, estimatedCpc: 0.25, audienceSize: '18M+', primaryReason: 'Indie rock heartland (Britpop, Shoegaze)', score: 99 },
    { code: 'US', name: 'United States', flag: '🇺🇸', estimatedCpm: 8.0, estimatedCpc: 0.60, audienceSize: '40M+', primaryReason: 'Huge indie/alternative market', score: 92 },
    { code: 'AU', name: 'Australia', flag: '🇦🇺', estimatedCpm: 3.8, estimatedCpc: 0.28, audienceSize: '8M+', primaryReason: 'Strong indie scene', score: 88 },
    { code: 'CA', name: 'Canada', flag: '🇨🇦', estimatedCpm: 4.0, estimatedCpc: 0.30, audienceSize: '10M+', primaryReason: 'Indie music capital (Montreal, Toronto)', score: 87 },
    { code: 'SE', name: 'Sweden', flag: '🇸🇪', estimatedCpm: 3.2, estimatedCpc: 0.23, audienceSize: '5M+', primaryReason: 'Spotify hometown, indie innovation', score: 86 },
  ],
  alternative: [
    { code: 'US', name: 'United States', flag: '🇺🇸', estimatedCpm: 8.0, estimatedCpc: 0.60, audienceSize: '50M+', primaryReason: 'Alt-rock heartland (Seattle, LA)', score: 98 },
    { code: 'GB', name: 'United Kingdom', flag: '🇬🇧', estimatedCpm: 3.5, estimatedCpc: 0.25, audienceSize: '20M+', primaryReason: 'Brit-rock, indie alternative powerhouse', score: 95 },
    { code: 'AU', name: 'Australia', flag: '🇦🇺', estimatedCpm: 3.8, estimatedCpc: 0.28, audienceSize: '10M+', primaryReason: 'Strong alternative rock culture', score: 88 },
    { code: 'CA', name: 'Canada', flag: '🇨🇦', estimatedCpm: 4.0, estimatedCpc: 0.30, audienceSize: '12M+', primaryReason: 'Alternative/grunge heritage', score: 87 },
    { code: 'DE', name: 'Germany', flag: '🇩🇪', estimatedCpm: 3.0, estimatedCpc: 0.22, audienceSize: '15M+', primaryReason: 'Krautrock and alternative scene', score: 83 },
  ],
  rock: [
    { code: 'US', name: 'United States', flag: '🇺🇸', estimatedCpm: 8.0, estimatedCpc: 0.60, audienceSize: '60M+', primaryReason: 'Rock birthplace', score: 99 },
    { code: 'GB', name: 'United Kingdom', flag: '🇬🇧', estimatedCpm: 3.5, estimatedCpc: 0.25, audienceSize: '25M+', primaryReason: 'British Invasion legacy', score: 97 },
    { code: 'DE', name: 'Germany', flag: '🇩🇪', estimatedCpm: 3.0, estimatedCpc: 0.22, audienceSize: '20M+', primaryReason: 'Rock-heavy market', score: 90 },
    { code: 'BR', name: 'Brazil', flag: '🇧🇷', estimatedCpm: 1.1, estimatedCpc: 0.08, audienceSize: '30M+', primaryReason: 'Massive rock fanbase, low CPM', score: 88 },
    { code: 'JP', name: 'Japan', flag: '🇯🇵', estimatedCpm: 4.0, estimatedCpc: 0.30, audienceSize: '20M+', primaryReason: 'J-Rock and international rock', score: 88 },
  ],
  classical: [
    { code: 'DE', name: 'Germany', flag: '🇩🇪', estimatedCpm: 3.0, estimatedCpc: 0.22, audienceSize: '15M+', primaryReason: 'Classical music heartland (Bach, Beethoven, Brahms)', score: 99 },
    { code: 'AT', name: 'Austria', flag: '🇦🇹', estimatedCpm: 2.5, estimatedCpc: 0.18, audienceSize: '3M+', primaryReason: 'Vienna Philharmonic, Mozart homeland', score: 98 },
    { code: 'JP', name: 'Japan', flag: '🇯🇵', estimatedCpm: 4.0, estimatedCpc: 0.30, audienceSize: '12M+', primaryReason: 'Classical music deeply embedded', score: 94 },
    { code: 'US', name: 'United States', flag: '🇺🇸', estimatedCpm: 8.0, estimatedCpc: 0.60, audienceSize: '20M+', primaryReason: 'Largest classical recording market', score: 87 },
    { code: 'GB', name: 'United Kingdom', flag: '🇬🇧', estimatedCpm: 3.5, estimatedCpc: 0.25, audienceSize: '10M+', primaryReason: 'BBC Proms, classical institution', score: 90 },
  ],
  default: [
    { code: 'US', name: 'United States', flag: '🇺🇸', estimatedCpm: 8.0, estimatedCpc: 0.60, audienceSize: '100M+', primaryReason: 'Largest music streaming market', score: 90 },
    { code: 'GB', name: 'United Kingdom', flag: '🇬🇧', estimatedCpm: 3.5, estimatedCpc: 0.25, audienceSize: '30M+', primaryReason: 'Major English-speaking market', score: 88 },
    { code: 'CA', name: 'Canada', flag: '🇨🇦', estimatedCpm: 4.0, estimatedCpc: 0.30, audienceSize: '18M+', primaryReason: 'High streaming engagement', score: 85 },
    { code: 'AU', name: 'Australia', flag: '🇦🇺', estimatedCpm: 3.8, estimatedCpc: 0.28, audienceSize: '12M+', primaryReason: 'Active music streaming market', score: 83 },
    { code: 'DE', name: 'Germany', flag: '🇩🇪', estimatedCpm: 3.0, estimatedCpc: 0.22, audienceSize: '20M+', primaryReason: 'Largest European music market', score: 82 },
  ],
};

// Map genre keywords to country map keys
export const GENRE_KEYWORD_MAP: Record<string, string> = {
  afrobeats: 'afrobeats',
  afropop: 'afrobeats',
  afro: 'afrobeats',
  amapiano: 'afrobeats',
  'k-pop': 'k-pop',
  kpop: 'k-pop',
  'korean pop': 'k-pop',
  latin: 'latin',
  reggaeton: 'reggaeton',
  cumbia: 'latin',
  salsa: 'latin',
  bachata: 'latin',
  'hip hop': 'hip-hop',
  'hip-hop': 'hip-hop',
  hiphop: 'hip-hop',
  rap: 'rap',
  trap: 'rap',
  drill: 'rap',
  'r&b': 'r&b',
  rnb: 'r&b',
  soul: 'soul',
  neo: 'r&b',
  edm: 'edm',
  'electronic dance': 'edm',
  house: 'edm',
  techno: 'edm',
  trance: 'edm',
  dubstep: 'edm',
  dance: 'dance',
  electronic: 'edm',
  jazz: 'jazz',
  blues: 'jazz',
  country: 'country',
  folk: 'country',
  americana: 'country',
  bluegrass: 'country',
  indie: 'indie',
  alternative: 'alternative',
  alt: 'alternative',
  rock: 'rock',
  metal: 'rock',
  punk: 'rock',
  grunge: 'rock',
  classical: 'classical',
  orchestral: 'classical',
  opera: 'classical',
  pop: 'pop',
};
