import type { DemographicTarget, InterestTarget } from '../../types';

// Age demographics per genre
export const GENRE_DEMOGRAPHICS: Record<string, DemographicTarget> = {
  afrobeats: {
    ageMin: 16,
    ageMax: 34,
    genderTargeting: 'all',
    primaryAgeRange: '18–28',
    reasoning: 'Afrobeats skews young (Gen Z and Millennials). High mobile usage, very social-share-oriented.',
  },
  'k-pop': {
    ageMin: 13,
    ageMax: 30,
    genderTargeting: 'all',
    primaryAgeRange: '15–25',
    reasoning: 'K-Pop fans are predominantly Gen Z. Highly engaged, follow streaming, and use social media heavily.',
  },
  latin: {
    ageMin: 16,
    ageMax: 40,
    genderTargeting: 'all',
    primaryAgeRange: '18–35',
    reasoning: 'Latin music has broad appeal. Strong 18–35 core, with some 35–40 legacy listeners.',
  },
  reggaeton: {
    ageMin: 16,
    ageMax: 35,
    genderTargeting: 'all',
    primaryAgeRange: '18–30',
    reasoning: 'Reggaeton is youthful and high-energy. Strong with 18–30 demographic.',
  },
  'hip-hop': {
    ageMin: 16,
    ageMax: 38,
    genderTargeting: 'all',
    primaryAgeRange: '18–32',
    reasoning: 'Hip-hop spans Gen Z and Millennials. Urban, culturally influential demographic.',
  },
  rap: {
    ageMin: 15,
    ageMax: 35,
    genderTargeting: 'all',
    primaryAgeRange: '17–30',
    reasoning: 'Rap audience is primarily young adults. Heavy streaming and playlist consumption.',
  },
  'r&b': {
    ageMin: 18,
    ageMax: 45,
    genderTargeting: 'all',
    primaryAgeRange: '22–38',
    reasoning: 'R&B has strong millennial and older Gen Z appeal. Emotionally resonant for 22–38.',
  },
  soul: {
    ageMin: 25,
    ageMax: 55,
    genderTargeting: 'all',
    primaryAgeRange: '28–45',
    reasoning: 'Soul music appeals to a slightly older, discerning audience. Strong 28–45 demographic.',
  },
  edm: {
    ageMin: 16,
    ageMax: 32,
    genderTargeting: 'all',
    primaryAgeRange: '18–28',
    reasoning: 'EDM is festival and party culture. Primarily young adults 18–28.',
  },
  dance: {
    ageMin: 16,
    ageMax: 35,
    genderTargeting: 'all',
    primaryAgeRange: '18–30',
    reasoning: 'Dance music is club-oriented. Strong 18–30 demographic.',
  },
  jazz: {
    ageMin: 25,
    ageMax: 60,
    genderTargeting: 'all',
    primaryAgeRange: '30–50',
    reasoning: 'Jazz has a more mature listener base. Strong 30–50 demographic with higher income.',
  },
  country: {
    ageMin: 20,
    ageMax: 55,
    genderTargeting: 'all',
    primaryAgeRange: '25–45',
    reasoning: 'Country music appeals to a wide age range. Core 25–45 demographic.',
  },
  indie: {
    ageMin: 18,
    ageMax: 40,
    genderTargeting: 'all',
    primaryAgeRange: '20–35',
    reasoning: 'Indie music is popular with college-educated Millennials and older Gen Z.',
  },
  alternative: {
    ageMin: 18,
    ageMax: 45,
    genderTargeting: 'all',
    primaryAgeRange: '20–38',
    reasoning: 'Alternative rock spans Millennial and Gen X. Loyal, streaming-active audience.',
  },
  rock: {
    ageMin: 20,
    ageMax: 55,
    genderTargeting: 'all',
    primaryAgeRange: '25–45',
    reasoning: 'Rock has broad age appeal. Core 25–45 with legacy listeners 45+.',
  },
  classical: {
    ageMin: 25,
    ageMax: 65,
    genderTargeting: 'all',
    primaryAgeRange: '30–55',
    reasoning: 'Classical listeners are typically older with higher education and income.',
  },
  pop: {
    ageMin: 13,
    ageMax: 40,
    genderTargeting: 'all',
    primaryAgeRange: '16–35',
    reasoning: 'Pop has the broadest demographic appeal. Strong across all ages from teens to 35.',
  },
  default: {
    ageMin: 18,
    ageMax: 45,
    genderTargeting: 'all',
    primaryAgeRange: '18–35',
    reasoning: 'General music audience. Broad targeting for maximum reach.',
  },
};

// Interest keywords per genre for Meta Ads targeting
export const GENRE_INTERESTS: Record<string, InterestTarget[]> = {
  afrobeats: [
    { id: '6002925', name: 'Afrobeats', category: 'Music' },
    { id: '6003367', name: 'Burna Boy', category: 'Artists' },
    { id: '6004558', name: 'Wizkid', category: 'Artists' },
    { id: '6005112', name: 'Davido', category: 'Artists' },
    { id: '6012244', name: 'African music', category: 'Music' },
    { id: '6000600', name: 'Spotify', category: 'Apps' },
    { id: '6003106', name: 'Music streaming', category: 'Technology' },
    { id: '6002140', name: 'Playlist', category: 'Music' },
  ],
  'k-pop': [
    { id: '6001966', name: 'K-pop', category: 'Music' },
    { id: '6002030', name: 'BTS', category: 'Artists' },
    { id: '6002031', name: 'BLACKPINK', category: 'Artists' },
    { id: '6003288', name: 'Korean culture', category: 'Culture' },
    { id: '6000600', name: 'Spotify', category: 'Apps' },
    { id: '6003106', name: 'Music streaming', category: 'Technology' },
    { id: '6002140', name: 'Playlist', category: 'Music' },
  ],
  'hip-hop': [
    { id: '6003348', name: 'Hip hop music', category: 'Music' },
    { id: '6003349', name: 'Rap music', category: 'Music' },
    { id: '6000600', name: 'Spotify', category: 'Apps' },
    { id: '6003106', name: 'Music streaming', category: 'Technology' },
    { id: '6002140', name: 'Playlist', category: 'Music' },
    { id: '6004023', name: 'Urban music', category: 'Music' },
    { id: '6001966', name: 'Street culture', category: 'Culture' },
  ],
  edm: [
    { id: '6002925', name: 'Electronic dance music', category: 'Music' },
    { id: '6003367', name: 'House music', category: 'Music' },
    { id: '6004558', name: 'Music festivals', category: 'Events' },
    { id: '6005112', name: 'Nightlife', category: 'Lifestyle' },
    { id: '6000600', name: 'Spotify', category: 'Apps' },
    { id: '6003106', name: 'Music streaming', category: 'Technology' },
    { id: '6002140', name: 'Playlist', category: 'Music' },
  ],
  default: [
    { id: '6000600', name: 'Spotify', category: 'Apps' },
    { id: '6003106', name: 'Music streaming', category: 'Technology' },
    { id: '6002140', name: 'Playlist', category: 'Music' },
    { id: '6004023', name: 'Music discovery', category: 'Music' },
    { id: '6001966', name: 'Online music', category: 'Music' },
  ],
};
