// ===================================================
// Analytics Export Utilities
// ===================================================

import type { AnalyticsSummary, PlatformMetrics, ROIReport } from './types';

// ===================================================
// JSON Export
// ===================================================

export function exportToJSON(payload: {
  summary: AnalyticsSummary;
  platforms: PlatformMetrics[];
  roi?: ROIReport;
}): void {
  const json = JSON.stringify(payload, null, 2);
  downloadFile(
    json,
    `analytics-report-${formatDateSlug()}.json`,
    'application/json'
  );
}

// ===================================================
// CSV Export
// ===================================================

export function exportToCSV(platforms: PlatformMetrics[]): void {
  const headers = [
    'Platform',
    'Impressions',
    'Clicks',
    'CTR (%)',
    'CPC ($)',
    'CPM ($)',
    'Spend ($)',
    'Conversions',
    'ROAS',
    'New Followers',
    'New Streams',
  ];

  const rows = platforms.map((p) => [
    p.label,
    p.impressions,
    p.clicks,
    p.ctr.toFixed(2),
    p.cpc.toFixed(2),
    p.cpm.toFixed(2),
    p.spend.toFixed(2),
    p.conversions,
    p.roas.toFixed(2),
    p.newFollowers,
    p.newStreams,
  ]);

  const csv = [headers, ...rows]
    .map((row) => row.map(csvEscape).join(','))
    .join('\n');

  downloadFile(
    csv,
    `analytics-report-${formatDateSlug()}.csv`,
    'text/csv;charset=utf-8;'
  );
}

// ===================================================
// Plain Text Summary
// ===================================================

export function generateSummaryText(
  summary: AnalyticsSummary,
  platforms: PlatformMetrics[]
): string {
  const lines: string[] = [
    '╔══════════════════════════════════════╗',
    '║     SPOTIFY AD CURATOR — ANALYTICS  ║',
    '╚══════════════════════════════════════╝',
    '',
    `Period: ${summary.periodLabel}`,
    `Generated: ${new Date().toLocaleDateString()}`,
    '',
    '── OVERALL PERFORMANCE ────────────────',
    `Total Spend:        $${summary.totalSpend.toLocaleString()}`,
    `Total Reach:        ${summary.totalReach.toLocaleString()} people`,
    `Total Impressions:  ${summary.totalImpressions.toLocaleString()}`,
    `Total Clicks:       ${summary.totalClicks.toLocaleString()}`,
    `Avg CTR:            ${summary.avgCtr.toFixed(2)}%`,
    `Conversions:        ${summary.totalConversions.toLocaleString()}`,
    `Cost/Follower:      $${summary.costPerFollower.toFixed(2)}`,
    `Cost/Stream:        $${summary.costPerStream.toFixed(4)}`,
    `Best Platform:      ${summary.bestPlatformLabel} 🏆`,
    '',
    '── PLATFORM BREAKDOWN ─────────────────',
    ...platforms.map(
      (p) =>
        `${p.label.padEnd(10)} | Spend $${p.spend.toFixed(0).padStart(6)} | CTR ${p.ctr.toFixed(2)}% | ROAS ${p.roas.toFixed(1)}x | ${p.newFollowers.toLocaleString()} followers`
    ),
    '',
    '── GENERATED BY SPOTIFY AD CURATOR ────',
  ];

  return lines.join('\n');
}

export function downloadSummaryText(
  summary: AnalyticsSummary,
  platforms: PlatformMetrics[]
): void {
  const text = generateSummaryText(summary, platforms);
  downloadFile(text, `analytics-summary-${formatDateSlug()}.txt`, 'text/plain');
}

// ===================================================
// Helpers
// ===================================================

function downloadFile(content: string, filename: string, mimeType: string): void {
  const blob = new Blob([content], { type: mimeType });
  const url  = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.setAttribute('href', url);
  link.setAttribute('download', filename);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

function formatDateSlug(): string {
  return new Date().toISOString().split('T')[0];
}

function csvEscape(value: string | number): string {
  const str = String(value);
  return str.includes(',') || str.includes('"') || str.includes('\n')
    ? `"${str.replace(/"/g, '""')}"`
    : str;
}
