// ===================================================
// Demo Service — Pre-built Scenarios
// ===================================================

import type { DemoScenario } from './types';

export const DEMO_SCENARIOS: DemoScenario[] = [
  {
    id: 'quick-start',
    name: 'Quick Start',
    description: 'Paste a Spotify link, see instant analysis, and generate your first ad in 2 minutes.',
    estimatedMinutes: 2,
    difficulty: 'beginner',
    icon: '🚀',
    steps: [
      {
        id: 'qs-1',
        title: 'Welcome!',
        text: 'This quick tour shows you the core workflow. We\'ll paste a sample Spotify link and generate a real ad campaign.',
        position: 'center',
        action: 'observe',
      },
      {
        id: 'qs-2',
        title: 'Paste a Spotify Link',
        text: 'Start by pasting any Spotify playlist, album, or artist URL into this input field. Demo mode uses a pre-loaded Afrobeats playlist.',
        targetSelector: '[data-demo="spotify-input"]',
        position: 'bottom',
        action: 'observe',
        navigateTo: 'landing',
      },
      {
        id: 'qs-3',
        title: 'See the Analysis',
        text: 'SpotifyAdCurator instantly analyzes genres, mood, tempo, popularity and top artists to build your audience profile.',
        targetSelector: '[data-demo="analysis-panel"]',
        position: 'right',
        action: 'navigate',
        navigateTo: 'dashboard',
      },
      {
        id: 'qs-4',
        title: 'Review Targeting',
        text: 'AI recommends the best countries, age ranges, and interest categories based on your playlist\'s genre and mood data.',
        targetSelector: '[data-demo="targeting-panel"]',
        position: 'right',
        action: 'navigate',
        navigateTo: 'targeting',
      },
      {
        id: 'qs-5',
        title: 'Generate Your Ad',
        text: 'The ad generator creates complete Meta campaigns with proven copywriting formulas. Your first ad is ready to export!',
        targetSelector: '[data-demo="ad-generator"]',
        position: 'top',
        action: 'navigate',
        navigateTo: 'ad-generator',
      },
    ],
    completionCriteria: 'Navigate through landing → dashboard → targeting → ad-generator',
  },
  {
    id: 'full-campaign',
    name: 'Full Campaign Builder',
    description: 'Build a complete multi-platform campaign across all 5 ad networks and export everything.',
    estimatedMinutes: 5,
    difficulty: 'intermediate',
    icon: '🎯',
    steps: [
      {
        id: 'fc-1',
        title: 'Full Campaign Walkthrough',
        text: 'We\'ll build a complete campaign across Meta, TikTok, YouTube, Google, and generate AI copy — all from one playlist.',
        position: 'center',
        navigateTo: 'dashboard',
      },
      {
        id: 'fc-2',
        title: 'Meta Ads Tab',
        text: 'Start with Meta (Facebook + Instagram). The ad generator creates campaign structures with carousel, video, and story formats.',
        targetSelector: '[data-demo="meta-tab"]',
        position: 'bottom',
        action: 'navigate',
        navigateTo: 'ad-generator',
      },
      {
        id: 'fc-3',
        title: 'TikTok Ads',
        text: 'Switch to TikTok. Templates are optimized for vertical video with trending audio hooks matched to your playlist\'s mood.',
        targetSelector: '[data-demo="tiktok-tab"]',
        position: 'bottom',
        action: 'observe',
      },
      {
        id: 'fc-4',
        title: 'YouTube Ads',
        text: 'YouTube skippable and bumper ads with targeting based on music genre and artist affinities.',
        targetSelector: '[data-demo="youtube-tab"]',
        position: 'bottom',
        action: 'observe',
      },
      {
        id: 'fc-5',
        title: 'Google Search & Display',
        text: 'Google Search campaigns with keyword clusters extracted from your playlist genres and artist names.',
        targetSelector: '[data-demo="google-tab"]',
        position: 'bottom',
        action: 'observe',
      },
      {
        id: 'fc-6',
        title: 'AI Copy Generator',
        text: 'Generate unlimited ad copy variations using GPT-powered templates tuned for music promotion.',
        targetSelector: '[data-demo="ai-copy-tab"]',
        position: 'bottom',
        action: 'observe',
      },
      {
        id: 'fc-7',
        title: 'Export All',
        text: 'Export your full campaign as JSON, CSV, or copy it directly to clipboard. All 5 platforms in one click.',
        targetSelector: '[data-demo="export-btn"]',
        position: 'left',
        action: 'observe',
      },
    ],
    completionCriteria: 'View all 5 platform tabs in the ad generator',
  },
  {
    id: 'platform-tour',
    name: 'Platform Tour',
    description: 'Walk through each ad platform tab with explanations of what makes each one unique.',
    estimatedMinutes: 3,
    difficulty: 'beginner',
    icon: '🗺️',
    steps: [
      {
        id: 'pt-1',
        title: 'Platform Tour',
        text: 'SpotifyAdCurator supports 5 ad platforms. Let\'s explore what\'s available on each one.',
        position: 'center',
        navigateTo: 'ad-generator',
      },
      {
        id: 'pt-2',
        title: 'Meta Ads (Facebook + Instagram)',
        text: 'Meta campaigns with carousel, single image, video, and story formats. Includes audience lookalikes from your listener base.',
        targetSelector: '[data-demo="meta-tab"]',
        position: 'bottom',
        action: 'navigate',
        navigateTo: 'ad-generator',
      },
      {
        id: 'pt-3',
        title: 'TikTok Spark Ads',
        text: 'TikTok TopView, In-Feed, and Brand Takeover formats. Music-sync templates match your playlist\'s BPM and energy level.',
        targetSelector: '[data-demo="tiktok-tab"]',
        position: 'bottom',
        action: 'observe',
      },
      {
        id: 'pt-4',
        title: 'YouTube Video Ads',
        text: 'Pre-roll, mid-roll, and bumper formats. Targets music fans by genre affinity, watched artists, and YouTube Music behavior.',
        targetSelector: '[data-demo="youtube-tab"]',
        position: 'bottom',
        action: 'observe',
      },
      {
        id: 'pt-5',
        title: 'Google Search & Display',
        text: 'Search ads capture intent ("best afrobeats playlist 2024"). Display retargets anyone who\'s visited your Spotify profile.',
        targetSelector: '[data-demo="google-tab"]',
        position: 'bottom',
        action: 'observe',
      },
      {
        id: 'pt-6',
        title: 'AI Copy Generator',
        text: 'Not a platform per se, but generates copy for all platforms simultaneously. Choose tone, length, and CTA style.',
        targetSelector: '[data-demo="ai-copy-tab"]',
        position: 'bottom',
        action: 'observe',
      },
    ],
    completionCriteria: 'Visit all platform tabs',
  },
  {
    id: 'analytics-deep-dive',
    name: 'Analytics Deep Dive',
    description: 'Explore the analytics dashboard with 30 days of sample campaign performance data.',
    estimatedMinutes: 3,
    difficulty: 'intermediate',
    icon: '📊',
    steps: [
      {
        id: 'ad-1',
        title: 'Analytics Dashboard',
        text: 'The analytics dashboard shows real-time campaign performance across all platforms in one view.',
        position: 'center',
        navigateTo: 'analytics',
      },
      {
        id: 'ad-2',
        title: 'Performance Overview',
        text: 'Top-line KPIs: impressions, clicks, conversions, spend, and ROAS — all with week-over-week comparison.',
        targetSelector: '[data-demo="analytics-overview"]',
        position: 'bottom',
        action: 'navigate',
        navigateTo: 'analytics',
      },
      {
        id: 'ad-3',
        title: 'Platform Breakdown',
        text: 'Compare performance across platforms side by side. See which platform delivers the best CPM, CPC, and conversion rate.',
        targetSelector: '[data-demo="platform-chart"]',
        position: 'top',
        action: 'observe',
      },
      {
        id: 'ad-4',
        title: 'Genre Correlation',
        text: 'See which genres in your playlist drive the most ad engagement. Afrobeats might outperform on TikTok; R&B on YouTube.',
        targetSelector: '[data-demo="genre-chart"]',
        position: 'top',
        action: 'observe',
      },
      {
        id: 'ad-5',
        title: 'Audience Insights',
        text: 'Demographics, devices, and geographic breakdown of your campaign reach. Use this to refine targeting.',
        targetSelector: '[data-demo="audience-chart"]',
        position: 'left',
        action: 'observe',
      },
    ],
    completionCriteria: 'View the analytics dashboard',
  },
  {
    id: 'power-user',
    name: 'Power User',
    description: 'Master the advanced tools: Scheduler, Reels Studio, AI Copy, and Payments flow.',
    estimatedMinutes: 5,
    difficulty: 'advanced',
    icon: '⚡',
    steps: [
      {
        id: 'pu-1',
        title: 'Power User Tour',
        text: 'You\'ve mastered the basics. This tour covers the advanced features that set SpotifyAdCurator apart.',
        position: 'center',
        navigateTo: 'scheduler',
      },
      {
        id: 'pu-2',
        title: 'Auto-Refresh Scheduler',
        text: 'Set campaigns to auto-pause losers, boost winners, and refresh copy on a schedule. Set it and forget it.',
        targetSelector: '[data-demo="scheduler-dashboard"]',
        position: 'right',
        action: 'navigate',
        navigateTo: 'scheduler',
      },
      {
        id: 'pu-3',
        title: 'Performance Rules',
        text: 'Define thresholds: pause ads with CTR < 0.5%, boost ads with ROAS > 3x. Rules run automatically.',
        targetSelector: '[data-demo="performance-rules"]',
        position: 'top',
        action: 'observe',
      },
      {
        id: 'pu-4',
        title: 'Reels Studio',
        text: 'Generate shot lists and storyboards for Instagram Reels, TikTok, and YouTube Shorts from your playlist.',
        targetSelector: '[data-demo="reels-gallery"]',
        position: 'right',
        action: 'navigate',
        navigateTo: 'reels-studio',
      },
      {
        id: 'pu-5',
        title: 'Template Editor',
        text: 'Customize section timings, text overlays, color palettes, and animation styles for each video segment.',
        targetSelector: '[data-demo="template-editor"]',
        position: 'left',
        action: 'observe',
      },
      {
        id: 'pu-6',
        title: 'Pro Plans & Billing',
        text: 'Upgrade to Pro or Agency tier to unlock unlimited exports, API access, white-label reports, and priority support.',
        targetSelector: '[data-demo="pricing-plans"]',
        position: 'top',
        action: 'navigate',
        navigateTo: 'pricing',
      },
    ],
    completionCriteria: 'Visit scheduler, reels-studio, and pricing pages',
  },
];

export const getScenarioById = (id: string): DemoScenario | undefined =>
  DEMO_SCENARIOS.find((s) => s.id === id);
