import type { PlaylistAnalysis, TargetingRecommendation, AdCampaign } from '../types';

export const DEMO_ANALYSIS: PlaylistAnalysis = {
  playlist: {
    id: 'demo-playlist-001',
    name: 'Afrobeats Hits 2024 🌍',
    description: 'The hottest Afrobeats and Afro-pop bangers, curated weekly with the freshest tracks from Nigeria, Ghana, and across the diaspora.',
    imageUrl: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=400&h=400&fit=crop',
    followerCount: 47823,
    trackCount: 45,
    totalDurationMs: 9450000,
    spotifyUrl: 'https://open.spotify.com/playlist/37i9dQZF1DX3LDIBRoaCDQ',
  },
  genres: [
    { genre: 'Afrobeats', count: 28, percentage: 0.42 },
    { genre: 'Afropop', count: 18, percentage: 0.27 },
    { genre: 'Nigerian Pop', count: 10, percentage: 0.15 },
    { genre: 'Afroswing', count: 6, percentage: 0.09 },
    { genre: 'Dancehall', count: 4, percentage: 0.06 },
    { genre: 'R&B', count: 1, percentage: 0.01 },
  ],
  topGenre: 'Afrobeats',
  popularityStats: {
    average: 68,
    min: 42,
    max: 94,
    distribution: [
      { range: '0-20', count: 0 },
      { range: '21-40', count: 2 },
      { range: '41-60', count: 12 },
      { range: '61-80', count: 22 },
      { range: '81-100', count: 9 },
    ],
  },
  moodProfile: {
    energy: 0.78,
    danceability: 0.85,
    valence: 0.72,
    acousticness: 0.12,
    instrumentalness: 0.03,
    tempo: 114,
    label: 'Energetic & Happy 🔥😊',
    description: 'High-energy, feel-good vibes that get you moving',
  },
  topArtists: [
    { id: 'a1', name: 'Burna Boy', trackCount: 6, popularity: 87, imageUrl: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=100&h=100&fit=crop' },
    { id: 'a2', name: 'Wizkid', trackCount: 5, popularity: 84, imageUrl: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=100&h=100&fit=crop' },
    { id: 'a3', name: 'Davido', trackCount: 4, popularity: 79, imageUrl: 'https://images.unsplash.com/photo-1614680376573-df3480f0c6ff?w=100&h=100&fit=crop' },
    { id: 'a4', name: 'Rema', trackCount: 4, popularity: 82, imageUrl: 'https://images.unsplash.com/photo-1571330735066-03aaa9429d89?w=100&h=100&fit=crop' },
    { id: 'a5', name: 'Ayra Starr', trackCount: 3, popularity: 75, imageUrl: 'https://images.unsplash.com/photo-1487180144351-b8472da7d491?w=100&h=100&fit=crop' },
    { id: 'a6', name: 'Asake', trackCount: 3, popularity: 76, imageUrl: 'https://images.unsplash.com/photo-1527980965255-d3b416303d12?w=100&h=100&fit=crop' },
    { id: 'a7', name: 'Fireboy DML', trackCount: 3, popularity: 72, imageUrl: 'https://images.unsplash.com/photo-1463453091185-61582044d556?w=100&h=100&fit=crop' },
    { id: 'a8', name: 'Omah Lay', trackCount: 3, popularity: 71, imageUrl: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100&h=100&fit=crop' },
    { id: 'a9', name: 'Tems', trackCount: 2, popularity: 83, imageUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=100&h=100&fit=crop' },
    { id: 'a10', name: 'Black Sherif', trackCount: 2, popularity: 70, imageUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop' },
  ],
  genreDiversityScore: 0.6,
  analyzedAt: new Date().toISOString(),
};

export const DEMO_TARGETING: TargetingRecommendation = {
  countries: [
    { code: 'NG', name: 'Nigeria', flag: '🇳🇬', estimatedCpm: 0.8, estimatedCpc: 0.05, audienceSize: '12M+', primaryReason: 'Origin market, highest organic affinity', score: 98 },
    { code: 'GH', name: 'Ghana', flag: '🇬🇭', estimatedCpm: 0.7, estimatedCpc: 0.04, audienceSize: '3M+', primaryReason: 'Strong Afrobeats culture', score: 92 },
    { code: 'ZA', name: 'South Africa', flag: '🇿🇦', estimatedCpm: 1.2, estimatedCpc: 0.08, audienceSize: '5M+', primaryReason: 'Growing Afrobeats fanbase, low CPM', score: 85 },
    { code: 'GB', name: 'United Kingdom', flag: '🇬🇧', estimatedCpm: 3.5, estimatedCpc: 0.25, audienceSize: '8M+', primaryReason: 'Large diaspora, Afrobeats is mainstream', score: 88 },
    { code: 'US', name: 'United States', flag: '🇺🇸', estimatedCpm: 8.0, estimatedCpc: 0.60, audienceSize: '25M+', primaryReason: 'Huge African-American audience', score: 80 },
  ],
  demographics: {
    ageMin: 16,
    ageMax: 34,
    genderTargeting: 'all',
    primaryAgeRange: '18–28',
    reasoning: 'Afrobeats skews young (Gen Z and Millennials). High mobile usage, very social-share-oriented.',
  },
  interests: [
    { id: '6002925', name: 'Afrobeats', category: 'Music' },
    { id: '6003367', name: 'Burna Boy', category: 'Artists' },
    { id: '6004558', name: 'Wizkid', category: 'Artists' },
    { id: '6005112', name: 'Davido', category: 'Artists' },
    { id: '6012244', name: 'African music', category: 'Music' },
    { id: '6000600', name: 'Spotify', category: 'Apps' },
    { id: '6003106', name: 'Music streaming', category: 'Technology' },
    { id: '6002140', name: 'Playlist', category: 'Music' },
  ],
  budgetRecommendation: {
    dailyBudget: 2,
    currency: 'USD',
    estimatedReach: { min: 800, max: 2400 },
    estimatedImpressions: { min: 2000, max: 5000 },
    estimatedLinkClicks: { min: 15, max: 45 },
    topCountries: [
      { code: 'NG', name: 'Nigeria', flag: '🇳🇬', estimatedCpm: 0.8, estimatedCpc: 0.05, audienceSize: '12M+', primaryReason: 'Origin market, highest organic affinity', score: 98 },
      { code: 'GH', name: 'Ghana', flag: '🇬🇭', estimatedCpm: 0.7, estimatedCpc: 0.04, audienceSize: '3M+', primaryReason: 'Strong Afrobeats culture', score: 92 },
      { code: 'ZA', name: 'South Africa', flag: '🇿🇦', estimatedCpm: 1.2, estimatedCpc: 0.08, audienceSize: '5M+', primaryReason: 'Growing Afrobeats fanbase', score: 85 },
    ],
    notes: [
      '💡 Start with $1–3/day using Advantage+ placements for lowest CPM',
      '🎯 Use Lowest Cost bidding to maximize reach within budget',
      '📍 Nigeria + Ghana will give you the best ROI for Afrobeats',
      '⏱ Run ads for at least 7 days before evaluating performance',
      '🔄 A/B test at least 2 ad creatives simultaneously',
    ],
  },
  primaryGenre: 'Afrobeats',
  confidence: 0.88,
  generatedAt: new Date().toISOString(),
};

export const DEMO_CAMPAIGN: AdCampaign = {
  id: 'demo-campaign-001',
  name: '🎵 Afrobeats Hits 2024 — Afrobeats Growth Campaign',
  objective: 'LINK_CLICKS',
  status: 'DRAFT',
  dailyBudget: 2,
  specialAdCategories: [],
  adSets: [
    {
      name: 'Afrobeats Listeners — NG, GH, ZA, GB, US — Demo',
      dailyBudget: 200,
      bidStrategy: 'LOWEST_COST_WITHOUT_CAP',
      objective: 'LINK_CLICKS',
      startTime: new Date(Date.now() + 86400000).toISOString(),
      targeting: {
        geoLocations: { countries: ['NG', 'GH', 'ZA', 'GB', 'US'] },
        ageMin: 16,
        ageMax: 34,
        interests: [
          { id: '6002925', name: 'Afrobeats' },
          { id: '6003367', name: 'Burna Boy' },
          { id: '6004558', name: 'Wizkid' },
        ],
        publisherPlatforms: ['facebook', 'instagram'],
        facebookPositions: ['feed', 'marketplace'],
        instagramPositions: ['stream', 'story', 'reels'],
      },
      optimizationGoal: 'LINK_CLICKS',
      billingEvent: 'IMPRESSIONS',
    },
  ],
  creatives: [
    {
      id: 'template-1',
      name: '🎵 Discovery Hook',
      primaryText: '🌍 Discover Afrobeats vibes you\'ll absolutely love ❤️\n\nHandpicked tracks, curated with soul. This playlist doesn\'t miss — every song hits different.\n\n🎧 45 tracks of pure Afrobeats perfection\n✨ Follow the playlist, change your mood instantly',
      headline: 'Your New Favorite Afrobeats Playlist ❤️',
      description: '45 handpicked Afrobeats tracks • Follow now',
      callToAction: 'Listen Now',
      imageSpecs: {
        recommended: '1080x1080px (square) or 1200x628px (landscape)',
        aspectRatio: '1:1 or 1.91:1',
        minWidth: 600,
        minHeight: 600,
      },
      placements: ['facebook_feed', 'instagram_feed', 'instagram_stories'],
    },
    {
      id: 'template-2',
      name: '🔥 FOMO / Track Count',
      primaryText: '🔥 45 tracks handpicked for Energetic lovers 🔥\n\nEveryone\'s been streaming this playlist on repeat. You\'re missing out if you haven\'t heard it yet.\n\n❤️ Curated for real Afrobeats fans\n🎵 New tracks added regularly\n📈 Join thousands of listeners',
      headline: '45 Afrobeats Tracks You Need 🔥',
      description: 'Don\'t sleep on this • Energetic & Happy vibes',
      callToAction: 'Listen Now',
      imageSpecs: {
        recommended: '1080x1080px (square) or 1200x628px (landscape)',
        aspectRatio: '1:1 or 1.91:1',
        minWidth: 600,
        minHeight: 600,
      },
      placements: ['facebook_feed', 'instagram_feed'],
    },
  ],
  generatedAt: new Date().toISOString(),
  playlistName: 'Afrobeats Hits 2024 🌍',
  genre: 'Afrobeats',
};
